/// Flutter icons SignIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SignIcons
///      fonts:
///       - asset: fonts/SignIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SignIcons {
  SignIcons._();

  static const _kFontFam = 'SignIcons';
  static const String? _kFontPkg = null;

  static const IconData a_sign = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a_sign_2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a_sign_3 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a_sign_4 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData b_sign = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData b_sign_2 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData b_sign_3 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData b_sign_4 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c_sign = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c_sign_2 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c_sign_3 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c_sign_4 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData d_sign = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData d_sign_2 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData d_sign_3 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData d_sign_4 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData e_sign = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData e_sign_2 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData e_sign_3 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData e_sign_4 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData f_sign = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData f_sign_2 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData f_sign_3 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData f_sign_4 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData g_sign = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData g_sign_2 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData g_sign_3 = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData g_sign_4 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData h_sign = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData h_sign_2 = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData h_sign_3 = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData h_sign_4 = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i_sign = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i_sign_2 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i_sign_3 = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i_sign_4 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData j_sign = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData j_sign_2 = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData j_sign_3 = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData j_sign_4 = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData k_sign = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData k_sign_2 = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData k_sign_3 = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData k_sign_4 = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l_sign = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l_sign_2 = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l_sign_3 = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l_sign_4 = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData m_sign = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData m_sign_2 = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData m_sign_3 = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData m_sign_4 = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nn_sign = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData n_sign = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData n_sign_2 = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData n_sign_3 = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData n_sign_4 = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number_0 = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number_1 = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number_2 = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number_3 = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number_4 = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number_5 = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number_6 = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number_7 = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number_8 = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number_9 = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData number_10 = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData o_sign = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData o_sign_2 = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData o_sign_3 = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData o_sign_4 = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData p_sign = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData p_sign_2 = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData p_sign_3 = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData p_sign_4 = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData q_sign = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData q_sign_2 = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData q_sign_3 = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData q_sign_4 = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r_sign = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r_sign_2 = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r_sign_3 = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r_sign_4 = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s_sign = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s_sign_2 = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s_sign_3 = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s_sign_4 = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t_sign = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t_sign_2 = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t_sign_3 = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t_sign_4 = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData u_sign = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData u_sign_2 = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData u_sign_3 = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData u_sign_4 = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData v_sign = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData v_sign_2 = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData v_sign_3 = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData v_sign_4 = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData w_sign = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData w_sign_2 = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData w_sign_3 = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData w_sign_4 = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_sign = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_sign_2 = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_sign_3 = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_sign_4 = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y_sign = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y_sign_2 = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y_sign_3 = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y_sign_4 = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData z_sign = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData z_sign_2 = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData z_sign_3 = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData z_sign_4 = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
